language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install: true
script: 
  - ./build/linux/build.sh
  - ./build/linux/test.sh
before_deploy:
  - rm -r ./src ./build ./node_modules 
  - rm README.md package-lock.json karma.config.js webpack.config.js
deploy:
  provider: heroku
  skip_cleanup: true
  app: junior-dev-jobs
  api_key:
    secure: "tO3EMNt0BffkpVdyy5ISr39JDPE7WNx3zpH5uLW0pUStM3rUI8tx4Dl4MHlXClluPMd81t5pRYJ1BBXanJezASp73qzZQjjOBm8bWBcEoceAnEFv2L5PnemMedIFEp8WHJ74IwWQdIaJt025MbPbtsUMq6Cpr8oQPE9EJ2IiKlpe24YRS7yoCfwxu39KymXiBl2UuusBB9h6U4XIziL+bMotwWUYsjqSj8kx15iHx/j31PCxlJukgWFfHmxLd5GgCO4kvaFPcxxzOvizT1bCHw1goRRGk9xMo953WvfOemmC2Rc3g7qRVaG8DA+icZ5c4OAzg4gUQqv4Xwa3RSBlT3e3SchnfcDtPU5hawdDjZaveAF0IDBlWQBv7l21RpiOtLPi3T//H/JdMobW29HsmpmFIeuroCX/6JSGAhQEZcjy/nxI9H5rI6m1a+CCVIwU9n0TwHlG2E7qCFQkjnTf8p+HS5XCp0xRLd23byjBFidsnnx+hnbMXaTy5/hu2qZs8FxQ1S04HNibtzsNjG1Cwd1sVmSfF0knNBx6ubMyXHSSWZAX0xTx3YbiQAGY0MsuEPHGY8h8XMj33OLgszKQ6HbF2anP1MKJSLavOiFdQb/tMobDyfDwMUUlkcqxYgzqLDm0CpJhgsSIJ6SHJp9USIEyzrdcH2nK30ulfcLu4iw="
  on:
    all_branches: true