language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install: true
script:
- "./build/linux/build.sh"
- "./build/linux/test.sh"
deploy:
    provider: "heroku"
        app: chloe-jdjobs-dev
        api_key:
            secure: OfuZcI3sT8bnp4K0qDt1oxrtPY8yZcYjoouSJfrsJNmVBbR8UWv7fYTVJiJLyhqCuUBCeETrCg1THw7KMuFy2G0cf/XpqQ1fXnkGaqyMPT9xDiE+hFZz427b84VR5PwxOTX1VbpHcyi37Ebu0b5ZIJ18zDn4Ccw3fsdk1JfbuT4QQKREFtYMNHTfWmgos4OkzrCMHbPt5E+5w2BeDUscdCmeMzb0Poc0f60cZ0aJ2/Z6g7lpI7YfcA02PI65KxD6zdblI/ZO9N1hGnelr/0P2+Ur1UB3rOfUVwz2sjsAxMqsbLzFzDymVDVI1ODuF6XPUhUpaMK9hZY28brxIXS+Spn+5dpsH9PsMKdTbs71F7Q/hxFs9tVWa5r9DktzrxzZvI4xeFgLK7NU87ZPvOtVC28GBpJNAuQTQelpkvKUhTiTkzA0WGFFtlAqWp6WLIc68SdflzSoFGDMNAgaabWnFQeKmVVr+CPLgxYjsmBMtUUVv140EeShBYAL/QuJy6nM9tBL6VZ/6yLvZncmU40MK5/a5dbUzbFfswZhEKxxCBSvJRMuR73YGsYDWnZRYohkSSHxWeY9mJGRZ24f/i29k3Ztj2fcAVYumIme4vWt237RqgIcuhdEhw/MWVLPI0DCdRzgpNIkcQiFe5TEpyxeXecTs4qMhjN7b5Wi/etUmeI=
    on:
        all_branches: true
